---
title: How does a CPU work 2? Overview
date: 2023-05-14
tags: ['draft']
category: "digital_logic_2"
type: 'docs'
link:
description:
identifier: digital_logic_2
weight: 20
bookHidden: true
overview: true
---
{{< katex />}}
== How does a CPU work 2 - Table of contents


==  *From Combinatorial to Sequential Logic - Introduction*
_link:/pages/10_sequential_logic[Introduction to Sequential Logic]_

We get from purely conmbinatorial logic circuits wihout any form of memeory to sequential logic circuits with some
type of memory (mostly flipflops)

==  *Clocks,Flipflops and registers*

_link:/pages/11_clocks_and_registers/[Clocks,flipflops and registers]_

We make a leap into the area of sequential logic and introduce some concepts vital  for the sequential logics,
like clock, flipflops and registers

==  *Automata*

_link:/pages/12_automata/[Automata]_

We introduce the two (three) different automata Mealy, Moore (and Medwedjew). Those can be synchronous or
asynchronous.


==  *CPU Control*

_link:/pages/13_cpu_control/[CPU control]_

Here we are dissecting the brain of a CPU, the control unit, which handles and controls all actions
of a cpu

==  *Programmable Logic*

_link:/pages/14_programmable_logic/[Programmable Logic]_

We introduce the concept of programmable logic for both, combinatorial and sequential logic.


==  *Test thoroughly*

_link:/pages/15_testable_logic/[Testable Logic]_

Every embedded circuit or logic needs some infrastructure for testing. Here we introduce
JTAG and boundary-scan-tests.


==  *HDLs*

_VHDL and Verilog_

We introduce the concept of a Hardware Description Language (HDL) like VHDL and Verilog.


= Extra

==  *Register-Transfer-Level*

_Register-Transfer-Level_

In this lesson we introduce the concept of the register transfer level.



