---
title: 11_sequential_logic
date: 2023-05-01
weight: 110
category: "digital_logic_2"
link:
description:
type: text
bookHidden: true
menu:
  docs:
    parent: "digital_logic_2"
---
{{< katex />}}

== Sequential Logic

Complementary to Combinatorial logic, sequential logic contains some type of memory,
making the behaviour state-dependent. We need to feed it a clock signal.

image:./sequential_logic.svg[width=50%]

=== Mealy and Moore Automata (synchronous)
There are two different types of finite automata in the digital logic.
Those are:

. The mealy automata, which is dependent on the input and the state
. The moore automata, which is only dependent on the state

image:./mealy_logic.svg[width=50%]
image:./moore_logic.svg[width=50%]

=== Synchronous and Asynchronous sequential Logic

There are two different types of sequential logic, the synchronous sequential logic
with one central clock, as well as the asnychonous logic which has multiple clock
domains.

image:./sequential_logic2.svg[width=50%]

When we add a clock function to our automata shown above the synchronous
automata becomes an asynchronous automata.