---
title: 10_sequential_logic (de)
date: 2023-05-01
category: "digital_logik_2"
link:
description:
type: text
menu:
  docs:
    parent: "digital_logic_2"
    weight: 10
---
{{< katex />}}
== Sequentielle Logik

Ergänzend zur kombinatorischen Logik enthält die sequentielle Logik eine Art Speicher,
der das Verhalten zustandsabhängig macht. Wir müssen ihr ein Taktsignal zuführen.

image:./sequential_logic.svg[width=50%]

=== Mealy- und Moore-Automaten (synchron)
In der digitalen Logik gibt es zwei verschiedene Arten von endlichen Automaten.
Diese sind:

Der Mealy-Automat, der von der Eingabe und dem Zustand abhängig ist.
Der Moore-Automat, der nur vom Zustand abhängig ist

image:./mealy_logic.svg[width=50%]
image:./moore_logic.svg[width=50%]

=== Synchrone und asynchrone sequentielle Logik

Es gibt zwei verschiedene Arten sequentieller Logik: die synchrone sequentielle Logik
mit einem zentralen Taktgeber sowie die asnychrone Logik mit mehreren Taktgeber-Domänen.

image:./sequential_logic2.svg[width=50%]

Wenn wir unserem oben gezeigten Automaten eine Taktgeberfunktion hinzufügen, wird der synchrone Automat zum asynchronen Automaten.

(translation: 2024-12-29)