---
title: How does a CPU work? Overview
date: 2020-12-20
tags: ['draft']
type: 'docs'
category: "digital_logic_1"
link:
description:
identifier: digital_logic_1
weight: 10
---
{{< katex />}}
== How does a CPU work – Table of Contents

== *Introduction and Overview*

_Introduction and Overview_

Each topic in this course is divided into two parts:
one focusing on the mathematical side of digital logic—
ideally independent of implementation details—
and another more concrete part dealing with those very details.
In the concrete part, we will mostly discuss implementations
on the electrical level, although other solutions are possible,
such as those based on https://erik-engheim.medium.com/microprocessors-running-on-air-a47a702dd41f[fluid dynamics]
or https://www.photonics.com/Articles/All-Optical_Logic_Gates_Show_Promise_for_Optical/a63226[optical gates].

Most computers and logic gates are still based on electronics and semiconductor technology,
and this is unlikely to change with https://www.azom.com/article.aspx?ArticleID=17173[quantum computing],
which is largely related to probability theory. However, quantum computing would fundamentally
change the concepts discussed here.

== *Combinatorial Logic*

_link:/pages/00_combinatorial_logic[Introduction to Combinatorial Logic]_

A brief introduction to combinatorial logic and its various modeling approaches.

== *A First Look at Digital Logic*

_link:/pages/01_boolean_algebra/[Boolean Algebra, Basic Logic Gates and Their Implementation]_

In this lesson, we will explore truth tables and Boolean notation, and learn about
De Morgan’s laws. We will also examine basic logic gates and why they are typically
not implemented directly in electronics, focusing instead on NAND and NOR gates.

== *You Have to Choose!*

_link:/pages/02_xor/[A Complex Gate: XOR]_

Here we introduce another CPU operation and, as a side note and preparation for the next topic,
we examine the XOR gate. As before, we begin with the logical perspective and then look at
the electrical implementation.

== *01 + 01 = 10*

_link:/pages/03_binary_system[Binary Systems (Part I) and Combinatorial Logic (Part I)]_

We explain the basic concept of counting using only two states.
We'll also learn how to add two positive integers in the binary system,
derive the logic needed for a full adder, and take a deeper dive into combinatorial logic.

== *There Is Plenty of Room in the Negative Space*

_link:/pages/04_signs[Binary Systems (Part II): Signed Integers]_

The second part of our binary system discussion. Here we learn about one's and two's complement
representations, as well as how to perform subtraction.

== *Adding Is Not All*

_link:/pages/05_alu/[Combinatorial Logic (Part II): A Simple ALU]_

We conclude the first series with this second chapter on combinatorial logic.
Here, we expand the adder into a simple Arithmetic Logic Unit (ALU).

== *Outline: What Comes Next*

_From Combinatorial to Sequential Logic_

In this first course, we learned the basics of digital logic. But all examples so far
are based on static logic—we're still missing a way to store computed values.
To address this, we need to understand the concept of registers and sequential logic.
This will be the focus of the second part of the series.

= Extra

== *Let Me Look That Up*

_An Introduction to Memory and Look-Up Tables (LUTs)_

In this lesson, we learn that—at least in principle—every form of combinatorial logic
can be transformed into 'software' by storing it in memory. In a practical example,
we will show how a DDS sine wave generator uses a Look-Up Table (LUT) to replicate a sine wave.
