---
title: "Storytelling and the order of things"
slug: storytelling
date: 2025-07-12
tags:
category:
link:
description:
type: text
outdir: ~/development/blog
weight: 2000
bookHidden: true
overview: true

---

== Storytelling and the order of things

Hey reader,

today I want to talk with you about the (right) order of things and its importance.
When creating my first blog articles about electronics I hit multiple times the same obstacle, which is the order of things.

When trying to teach people about one of my favourite things I almost over the same amount of time, I am thinking about
the educational purpose to the reader.
That happened to me years ago, when I started this blog, and its happened to me ever since in a regular manner.
So, for the existing blog posts, I came up with the following order (starting with linear components): (1) Resistors,
then (2) capacitors and its counterpart coils, then - as last group, (3) - all the nonlinear components.
Last but not least we want to discuss integrated circuits (IC) which are made of all components before - with exception to the
coils which are hardly to made up in silicon.
For the nonlinear components I will also try to get an educational purposeful order, so we want start here with the diode,
then get to LEDs then  to (MOSFET) transistors...

